### ISSUE TITLE
ImportHelpers TS options breaks metadataDiscovery

### ISSUE THREAD

**Issue by NickBolles** [B4nan/mikro-orm#100]
Unconfirmed, but I think that using [`importHelpers`](https://github.com/Microsoft/tslib) breaks [lookupPathFromDecorator](https://github.com/B4nan/mikro-orm/blob/972c6e405738805b7204b783f0f609ce087a7b91/lib/utils/Utils.ts#L205)

It returns tslib.js as the source path and reports that it can't find tslib.ts

**Comment by B4nan** [comment]
Confirmed.

**Comment by B4nan** [comment]
Fix released as v2.7.6
