### ISSUE TITLE
Pull requests are not checked by Travis

### ISSUE THREAD

**Issue by pepakriz** [B4nan/mikro-orm#4]
Pull requests are not checked by Travis. Look at https://github.com/B4nan/mikro-orm/pull/3

**Comment by B4nan** [comment]
For me it looks like they are checked: https://travis-ci.org/B4nan/mikro-orm/builds/476410252 (not sure if that link is public, but I see your PR build results there).

![image](https://user-images.githubusercontent.com/615580/50778503-6a5b1e80-129e-11e9-8656-46587ad0f473.png)

**Comment by pepakriz** [comment]
Ok. Maybe they are checked, but they aren't connected to PRs

I mean this:
![image](https://user-images.githubusercontent.com/383294/50781873-c7f36900-12a6-11e9-8e96-c5314c58c6bb.png)

**Comment by B4nan** [comment]
I guess that is the new github apps integration. I migrated the repository to travis-ci.com and enable it.

**Comment by pepakriz** [comment]
It works, but PRs are doublechecked now.

![image](https://user-images.githubusercontent.com/383294/51020534-1f335b00-157f-11e9-91f9-9f613176969f.png)

**Comment by B4nan** [comment]
They are not double checked, this is travis issue in github integration, so please keep this closed. I did disable the deprecated one, not sure if it will help, let's see. 

More info here:

https://github.com/travis-ci/travis-ci/issues/10204
https://blog.travis-ci.com/2018-09-27-deprecating-github-commit-status-api-for-github-apps-managed-repositories
