### ISSUE TITLE
Is there any locking mechanism? 

### ISSUE THREAD

**Issue by vinverdy** [B4nan/mikro-orm#41]
is there any locking mechanism? is there any roadmap to implement it? It's really great project, hope many users will use this

**Comment by B4nan** [comment]
Hello there and thank you! 

Currently it is not implemented, and to be honest I have no experience with locking in other ORMs so far. Can you share some links? 

I am definitely open for implementing it, just need to first understand what and why is needed :]

**Comment by B4nan** [comment]
Something like this? https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/transactions-and-concurrency.html#locking-support

**Comment by vinverdy** [comment]
thanks for the fast response. yeah something like doctrine has implement, it will be great if implemented.

i think, this could explain the needs of locking. https://en.wikipedia.org/wiki/Concurrency_control#Why_is_concurrency_control_needed?

**Comment by B4nan** [comment]
Thanks for the link, I see this is needed, will try to look at this later.

**Comment by B4nan** [comment]
Do you think we need optimistic (app level) or pessimistic (dbal level) locking? or both approaches?

**Comment by vinverdy** [comment]
personally, i use optimistic locking for my application. But, i think, we need both approaches for mass market? but there is a problem with pessimistic locking in postgresql, the locking not support left join with null reference

**Comment by B4nan** [comment]
So it's almost ready, will be happy if you could review the code #57

**Comment by vinverdy** [comment]
wow, thank you so much for your great work. i thinks its already more than enough
