### ISSUE TITLE
logo contribution

### ISSUE THREAD

**Issue by reallinfo** [B4nan/mikro-orm#43]
Hello @B4nan .  I contribute to open source projects in my free time. You want me to design a logo for this repo? Actually, I have an idea. I can show you if you want. I will wait for feedback. Best regards.

**Comment by B4nan** [comment]
Hello there! Sure you can, would be nice to have something, as there is no image and when sharing via FB it looks like an error:] I would probably stick to that colours I have in docs (blue/green).

**Comment by reallinfo** [comment]
Sure :) I designed a logotype. I used a single letter 'o' for a cleaner look. I combined the letter O with the icon representing the database. The readme and docs views are also available in the following image. What do you think?

![mikrorm](https://user-images.githubusercontent.com/36298335/56057831-845a4080-5d68-11e9-979a-97dadba24583.jpg)

![mikro2](https://user-images.githubusercontent.com/36298335/56057844-8a502180-5d68-11e9-8d87-517f252de391.jpg)

![mikro](https://user-images.githubusercontent.com/36298335/56057848-90de9900-5d68-11e9-9353-60511bb9a05a.png)

**Comment by B4nan** [comment]
Thanks, looks nice! I would try to align the icon, also what about applying similar gradient to the icon as I have in docs (maybe from top to bottom rather than from side to side). Also I would probably not mix those two colors like this (gradient moght be fine, idk). Black and blue variant looks nice, maybe darker blue? 

I will experiment a bit myself tomorrow.

**Comment by reallinfo** [comment]
Oh ofcourse, i'll be looking forward to your selection of colors.  I will apply the color you want and  I will send a pull request.

**Comment by B4nan** [comment]
Could you please provide SVG code for this?

**Comment by reallinfo** [comment]
sure, here you are;

https://drive.google.com/open?id=1aEvbeUdTSIlWADKz8_4or96w0dWCIDpl

**Comment by B4nan** [comment]
WDYT? A bit smaller db icon, color: #166788. 

![image](https://user-images.githubusercontent.com/615580/56079255-44d83680-5df2-11e9-9c41-efaa93dcf874.png)

Also I would use smaller version in navbar (all white as you proposed) - here is 200x35px (which is fine for most cases, just the smallest devices needs tweaking - 320px wide). 

![image](https://user-images.githubusercontent.com/615580/56079447-d3e64e00-5df4-11e9-8f1b-89045b76a4d6.png)

**Comment by reallinfo** [comment]
Oh it looks fine! :) Is there anything you want from me?

**Comment by B4nan** [comment]
It depends on if you want to become one of my very few collaborators and send a PR :] If you don't care, I will be happy to integrate this myself. 

Anyway, thanks a lot!

**Comment by reallinfo** [comment]
Of course I will send a pr. Please contact me if you even need logo for other projects. Please check it :)

https://github.com/B4nan/mikro-orm/pull/44
